2024-05-21 15:52:34 - app - INFO - Students retrieved successfully: count=3
2024-05-21 16:20:14 - app - INFO - Student created successfully: John Doe
2024-05-21 16:20:14 - app - ERROR - Internal server error: 1 validation errors:
  {'type': 'string_type', 'loc': ('response',), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
  File "/usr/local/lib/python3.10/dist-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "/usr/local/lib/python3.10/dist-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vano/PycharmProjects/http-qt/server/src/http_server/main.py", line 43, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 315, in app
    content = await serialize_response(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'string_type', 'loc': ('response',), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}

2024-05-21 16:20:14 - app - ERROR - Error in read_student endpoint: 404: Student not found
Traceback (most recent call last):
  File "/home/vano/PycharmProjects/http-qt/server/src/http_server/main.py", line 120, in read_student
    db_student = crud.get_student(db, student_id)
  File "/home/vano/PycharmProjects/http-qt/server/src/http_server/crud.py", line 13, in get_student
    raise HTTPException(status_code=404, detail="Student not found")
fastapi.exceptions.HTTPException: 404: Student not found
2024-05-21 16:20:14 - app - ERROR - Error in read_students endpoint: a bytes-like object is required, not 'NoneType'
Traceback (most recent call last):
  File "/home/vano/PycharmProjects/http-qt/server/src/http_server/main.py", line 106, in read_students
    student.photo = base64.b64encode(student.photo).decode("utf-8")
  File "/usr/lib/python3.10/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'NoneType'
2024-05-21 16:23:35 - app - INFO - Student created successfully: John Doe
2024-05-21 16:23:35 - app - INFO - Student deleted successfully: ID=12
2024-05-21 16:23:35 - app - ERROR - Error in read_student endpoint: 404: Student not found
Traceback (most recent call last):
  File "/home/vano/PycharmProjects/http-qt/server/src/http_server/main.py", line 120, in read_student
    db_student = crud.get_student(db, student_id)
  File "/home/vano/PycharmProjects/http-qt/server/src/http_server/crud.py", line 13, in get_student
    raise HTTPException(status_code=404, detail="Student not found")
fastapi.exceptions.HTTPException: 404: Student not found
2024-05-21 16:23:35 - app - ERROR - Error in read_students endpoint: a bytes-like object is required, not 'NoneType'
Traceback (most recent call last):
  File "/home/vano/PycharmProjects/http-qt/server/src/http_server/main.py", line 106, in read_students
    student.photo = base64.b64encode(student.photo).decode("utf-8")
  File "/usr/lib/python3.10/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'NoneType'
2024-05-21 16:25:34 - app - INFO - Student created successfully: Ivan
2024-05-21 17:06:01 - app - INFO - Student created successfully: Баринов А
2024-05-21 17:06:47 - app - ERROR - Error in read_students endpoint: a bytes-like object is required, not 'NoneType'
Traceback (most recent call last):
  File "/home/vano/PycharmProjects/http-qt/server/src/http_server/main.py", line 106, in read_students
    student.photo = base64.b64encode(student.photo).decode("utf-8")
  File "/usr/lib/python3.10/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'NoneType'
2024-05-21 17:07:01 - app - ERROR - Error in read_student endpoint: 404: Student not found
Traceback (most recent call last):
  File "/home/vano/PycharmProjects/http-qt/server/src/http_server/main.py", line 120, in read_student
    db_student = crud.get_student(db, student_id)
  File "/home/vano/PycharmProjects/http-qt/server/src/http_server/crud.py", line 13, in get_student
    raise HTTPException(status_code=404, detail="Student not found")
fastapi.exceptions.HTTPException: 404: Student not found
2024-05-21 17:07:13 - app - INFO - Student retrieved successfully: Грунин А.А.
2024-05-21 17:07:16 - app - INFO - Student retrieved successfully: Грунин А.А.
